language: node_js
sudo: false
dist: trusty
node_js:
  - "7"
jobs:
  include:
    - stage: Install
      before_install:
        - npm install -g gulp-cli
      script:
        - gulp
    - stage: Unit Tests
      script:
        - npm test
